### ISSUE TITLE
Can't login after installation, no password seems to be valid

### ISSUE THREAD

**Issue by hoshy42** [UnauthorizedAccessBV/ESET-Protect-Docker-Server#2]
Can't login with any password or even change it :../
root, server and webinterface passwords are NOT `eraadmin`

Here is my story:
the short version:

 * Containers for server, console and SQL are installed via docker-compose
 * Login with default password "eraadmin" not possible on console (or anywhere really)
 * Trying to change root / web password inside container yields different errors, even as root (-u 0) and has not changed any password (as far as i know).

Long version:
 * Installation of ESET server and console as docker container with the docker-compose.yml file from
   `https://hub.docker.com/r/esetnederland/eset-protect-server`
 * Installation of Server and Console and SQL initialisation runs without errors.
 * Login on the Web-Console with "Administrator / eraadmin"  does NOT work
 * Installation repeated several times with differrent environment variables, (can I even CHANGE the web password this way??)
 * Trying to change the password with the commands:
  `export NEW_PASSWORD=someNewPassword; 
   /opt/eset/RemoteAdministrator/Server/setup/installer_backup.sh --skip-license --server-root password='env:NEW_PASSWORD'`
   from
  `https://support.eset.com/de/kb6849-reset-the-eset-security-management-center-web-console-esmc-web-console-password-7x`
   ends up in lots of "Operation not permitted" messages --> No root access
   even with root access (-u 0 again) there always seem to be an issue eg. `Error: option --db-user-username was not specified`

Where is my mistake?
Where is the password stored? 
Can I change it in the mySQL database?? Where?

I am not getting it... sorry
I will happily provide ANY data you might need.

Thanks for the good work....
and for your time....

**Comment by dmaasland** [comment]
Can you share the compose file you are using?

**Comment by hoshy42** [comment]
Sure, it is the one from: https://hub.docker.com/r/esetnederland/eset-protect-server

Here you go:
`
version: '3'

services:
    mysql:
        image: mysql:8.0.17
        command: |
            --default-authentication-plugin=mysql_native_password
            --innodb-log-file-size=100M
            --innodb-log-files-in-group=2
            --max-allowed-packet=30M
            --bind-address=*
            --log_bin_trust_function_creators=1
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_USER=root
            - MYSQL_ROOT_PASSWORD=eraadmin
        volumes:
            - mysql:/var/lib/mysql
    eset-protect-server:
        image: esetnederland/eset-protect-server
        depends_on: 
            - mysql
        restart: unless-stopped
        environment:
            - DB_ADMIN_USERNAME=root
            - DB_ADMIN_PASSWORD=eraadmin
            - AD_USER_PASSWORD=root
            - AD_USER_name=eraadmin
        volumes:
            - eset-protect-server-config:/config
            - eset-protect-server-data:/data
            - eset-protect-server-logs:/logs
        ports: 
            - 2222:2222
    eset-protect-console:
        image: esetnederland/eset-protect-console
        depends_on: 
            - eset-protect-server
        restart: unless-stopped
        volumes:
            - eset-protect-console:/config
        ports: 
            - 8180:8080
volumes:
    mysql:
    eset-protect-server-config:
    eset-protect-server-data:
    eset-protect-server-logs:
    eset-protect-console:
`

the only thing i have changed is the host port of the console container, since port 8080 is already in use.
sorry, for this, can't get it to format properly....

thank you for your time

**Comment by dmaasland** [comment]
Ah, I've found a small bug in the default config. Try this compose file for now:

```
version: '3'

services:
    mysql:
        image: mysql:8.0.17
        command: |
            --default-authentication-plugin=mysql_native_password
            --innodb-log-file-size=100M
            --innodb-log-files-in-group=2
            --max-allowed-packet=30M
            --bind-address=*
            --log_bin_trust_function_creators=1
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_USER=root
            - MYSQL_ROOT_PASSWORD=eraadmin
        volumes:
            - mysql:/var/lib/mysql

    eset-protect-server:
        image: esetnederland/eset-protect-server
        depends_on: 
            - mysql
        restart: unless-stopped
        environment:
            - DB_ADMIN_USERNAME=root
            - DB_ADMIN_PASSWORD=eraadmin
        volumes:
            - eset-protect-server-config:/config
            - eset-protect-server-data:/data
            - eset-protect-server-logs:/logs
        ports: 
            - 2222:2222

    eset-protect-console:
        image: esetnederland/eset-protect-console
        depends_on: 
            - eset-protect-server
        restart: unless-stopped
        environment:
            - ESMC_SERVER=eset-protect-server
        volumes:
            - eset-protect-console:/config
        ports: 
            - 8180:8080

volumes:
    mysql:
    eset-protect-server-config:
    eset-protect-server-data:
    eset-protect-server-logs:
    eset-protect-console:
```

I'll try to push a fix tomorrow
